version: '3'

services:
  core:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements.txt
    container_name: shortener
    command: /bin/sh -c "python app.py"
    stdin_open: true
    tty: true
    environment:
      - SERVER_NAME=0.0.0.0:5000
      - DB_NAME=db.sqlite3
    volumes:
      - ./url_shortener:/app
    ports:
      - 5000:5000
    networks:
      - internal


networks:
  internal:
